[env]
TERM = "xterm-256color"

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.8
blur = true

[window.position]
x = 650
y = 500

[window.dimensions]
columns = 95
lines = 25

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 15

[general]
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]
